/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class backapp_nativelink_BackupC */

#ifndef _Included_backapp_nativelink_BackupC
#define _Included_backapp_nativelink_BackupC
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     backapp_nativelink_BackupC
 * Method:    createBackup
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_backapp_nativelink_BackupC_createBackup
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring);

/*
 * Class:     backapp_nativelink_BackupC
 * Method:    restoreBackup
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_backapp_nativelink_BackupC_restoreBackup
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     backapp_nativelink_BackupC
 * Method:    deleteBackup
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_backapp_nativelink_BackupC_deleteBackup
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
