/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class backapp_nativelink_Backup */

#ifndef _Included_backapp_nativelink_Backup
#define _Included_backapp_nativelink_Backup
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     backapp_nativelink_Backup
 * Method:    createBackup
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_backapp_nativelink_Backup_createBackup
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring);

/*
 * Class:     backapp_nativelink_Backup
 * Method:    restoreBackup
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_backapp_nativelink_Backup_restoreBackup
  (JNIEnv *, jobject, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
